name: Sync keymaps to website

on:
  push:
    paths:
      - 'ideavimrc.vim'
      - '*.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'evan-liu',
              repo: 'evan-liu.github.io',
              workflow_id: 'keymaps.yml',
              ref: 'main',
            })
